### ISSUE TITLE
Upgrade Script failing

### ISSUE THREAD

**Issue by garrettmachen1** [netbox-community/netbox#10005]
### NetBox version

v3.2.8

### Python version

3.10

### Steps to Reproduce

New Build attempting to perform Upgrade.py Script results in an error fails at manage.py script

### Expected Behavior

Successful completion of the upgrade.

### Observed Behavior

Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/backports/zoneinfo/_common.py", line 15, in load_tzdata
    return importlib_resources.open_binary(package_name, resource_name)
  File "/usr/lib/python3.8/importlib/resources.py", line 91, in open_binary
    return reader.open_resource(resource)
  File "<frozen importlib._bootstrap_external>", line 1053, in open_resource
FileNotFoundError: [Errno 2] No such file or directory: '/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/tzdata/zoneinfo/Europe/Kyiv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/timezone_field/__init__.py", line 1, in <module>
    from timezone_field.fields import TimeZoneField
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/timezone_field/fields.py", line 11, in <module>
    class TimeZoneField(models.Field):
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/timezone_field/fields.py", line 41, in TimeZoneField
    default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/timezone_field/fields.py", line 41, in <listcomp>
    default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
  File "/opt/netbox-3.2.8/venv/lib/python3.8/site-packages/backports/zoneinfo/_common.py", line 27, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
backports.zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Europe/Kyiv'

**Comment by Pelt10** [comment]
Duplacted of #9986
