### ISSUE TITLE
netbox_secretstore plugin does not install (ImportError: CustomFieldImportForm)

### ISSUE THREAD

**Issue by KRONNESAP** [netbox-community/netbox#11415]
### NetBox version

v3.3.6

### Python version

3.11

### Steps to Reproduce

1. I installed the v3.3.6 version of netbox following the official documentation
2. The system worked normally and pages opened on the frontend
3. Add plugin name netbox-secretstore in /opt/netbox/local_requirements.txt
4. Add to PLUGINS in NetBox configuration in /opt/netbox/netbox/netbox/configuration.py
5. Run the command ./venv/bin/pip install -r local_requirements.txt
6. Run the command ./venv/bin/python netbox/manage.py migrate

netbox-secretstore plugin version v1.4.1

### Expected Behavior

I expected the new plugin to install normallyI expected the new plugin to install normally

### Observed Behavior

An import error occurred......

(venv) root@allen:/opt/netbox# ./venv/bin/python3 netbox/manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox-3.3.6/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/netbox_secretstore/admin.py", line 5, in <module>
    from .forms import ActivateUserKeyForm
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/netbox_secretstore/forms/__init__.py", line 1, in <module>
    from .secrets import *
  File "/opt/netbox-3.3.6/venv/lib/python3.11/site-packages/netbox_secretstore/forms/secrets.py", line 8, in <module>
    from extras.forms import CustomFieldImportForm, CustomFieldFilterForm, CustomFieldBulkEditForm, CustomFieldForm, TagForm
ImportError: cannot import name 'CustomFieldImportForm' from 'extras.forms' (/opt/netbox-3.3.6/netbox/extras/forms/__init__.py)
(venv) root@allen:/opt/netbox#

**Comment by kkthxbye-code** [comment]
This is not a netbox problem. Either update netbox or install [v1.3.0 of netbox-secretsstore](https://github.com/DanSheps/netbox-secretstore/releases/tag/v1.3.0) - the version you are installing is only compatible with netbox 3.4.

**Comment by KRONNESAP** [comment]
@kkthxbye-code It's true. Thank you!
