### ISSUE TITLE
IP-addresses created via addition of FHRP group do not inherit default custom field values

### ISSUE THREAD

**Issue by olegbliaher** [netbox-community/netbox#11565]
### NetBox version

3.1.10

### Python version

3.9

### Steps to Reproduce

1. Create a boolean custom field with a certain default value, for example **False**, and assign it the `ipam | IP address`-model.
2. Add a new FHRP group (IPAM -> FHRP Groups) with a new, unused IP-address under **Virtual IP Address**.
3. The new IP-address object attached to the VHRP-group does not have the custom field set, which generates an error when running reports.

### Expected Behavior

I'd expect the new IP-address to have the default custom field value.

### Observed Behavior

An exception occurred: KeyError: 'my_custom_field' Traceback (most recent call last): File "/usr/lib/netbox/app/extras/reports.py", line 234, in run test_method() File "/usr/local/lib/netbox/reports/my_report.py", line 11, in test_for_field if ip.custom_field_data["my_custom_field"]: 'my_custom_field'

**Comment by atownson** [comment]
Related to #11040
