### ISSUE TITLE
Resizing a widget to the be the smallest possible width or height will cause the dashboard to throw an exception.

### ISSUE THREAD

**Issue by kkthxbye-code** [netbox-community/netbox#12106]
### NetBox version

v3.5.0-beta1

### Python version

3.10

### Steps to Reproduce

1. Resize any widget and make it as small as possible
2. Save

### Expected Behavior

Save without issue.

### Observed Behavior

The dashboard throws an exception:

Internal Server Error: /
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in innerers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_responseers/base.py", line 197, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)rgs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in viewric/base.py", line 103, in view
     return self.dispatch(request, *args, **kwargs)
   File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatchric/base.py", line 142, in dispatch
     return handler(request, *args, **kwargs)
   File "/opt/netbox/netbox/netbox/views/misc.py", line 36, in get
     dashboard = get_dashboard(request.user).get_layout()
   File "/opt/netbox/netbox/extras/models/dashboard.py", line 43, in get_layout_layout
     widget.set_layout(grid_item)
   File "/opt/netbox/netbox/extras/dashboard/widgets.py", line 61, in set_layoutt_layout
     self.width = grid_item['w']
 KeyError: 'w'

**Comment by abhi1693** [comment]
I removed all widgets, saved the layout and then tried adding a note with simple text and saw the same error

**Comment by kkthxbye-code** [comment]
> I removed all widgets, saved the layout and then tried adding a note with simple text and saw the same error

Just tried on the beta-demo and could not replicate. Please provide proper replication steps if it's actually related to this issue

**Comment by abhi1693** [comment]
It does not seem to be happening again but if you can pull the logs from your beta VM, you will see the error

**Comment by kkthxbye-code** [comment]
> It does not seem to be happening again but if you can pull the logs from your beta VM, you will see the error when I posted the comment

Don't you think a likely explanation is just that another person was using the beta-demo site at the same time and caused the error?
