### ISSUE TITLE
Add do extension to Jinja2 for Config Rendering

### ISSUE THREAD

**Issue by peterbaumert** [netbox-community/netbox#12378]
### NetBox version

v3.5.0

### Feature type

New functionality

### Proposed functionality

It would be great if the jinja2 do extension could be added, this would enable more flexibility in creating complex configuration templates.

Currently using do results in following error:
```
Traceback (most recent call last):
  File "/opt/netbox/netbox/dcim/views.py", line 2044, in get_extra_context
    rendered_config = config_template.render(context=context_data)
  File "/opt/netbox/netbox/extras/models/configs.py", line 252, in render
    output = template.render(**context)
  File "/opt/netbox/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/netbox/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "switches/roles/access-switch.j2", line 1, in top-level template code
  File "switches/base.j2", line 2, in top-level template code
  File "switches/roles/access-switch.j2", line 5, in block 'content'
  File "/opt/netbox/netbox/utilities/jinja2.py", line 28, in get_source
    if referenced_templates := find_referenced_templates(environment.parse(template_source)):
  File "/opt/netbox/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 8, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'do'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
```

### Use case

Writing more complex configuration templates.

### Database changes

None

### External dependencies

[jinja2 do extension](https://jinja.palletsprojects.com/en/3.0.x/extensions/#expression-statement)

**Comment by kkthxbye-code** [comment]
You can add environment parameters to the Config Template in the `Environment params` field.

`{'extensions': ['jinja2.ext.do']}`

The above seems to work. As such, I don't think there's anything to do here. I'll close this, if I misunderstood or it doesn't work for you, let me know.

**Comment by peterbaumert** [comment]
oh thank you, didn't find this in documentation
