### ISSUE TITLE
v3.5.0 Upgrade Fail

### ISSUE THREAD

**Issue by aledr** [netbox-community/netbox#12404]
### NetBox version

v3.5.0

### Python version

3.9

### Steps to Reproduce

Run upgrade to 3.5.0.

### Expected Behavior

Update success.

### Observed Behavior

```
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/home/netbox/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/management/commands/migrate.py", line 97, in handle
    self.check(databases=[database])
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/netbox/netbox/netbox/netbox/urls.py", line 8, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/home/netbox/netbox/netbox/extras/plugins/urls.py", line 31, in <module>
    urlpatterns = import_string(f"{plugin_path}.urls.urlpatterns")
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/nextbox_ui_plugin/urls.py", line 2, in <module>
    from . import views
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/nextbox_ui_plugin/views.py", line 8, in <module>
    from . import forms, filters
  File "/home/netbox/netbox/venv/lib64/python3.9/site-packages/nextbox_ui_plugin/forms.py", line 3, in <module>
    from utilities.forms import (
ImportError: cannot import name 'DynamicModelMultipleChoiceField' from 'utilities.forms' (/home/netbox/netbox/netbox/utilities/forms/__init__.py)
```

**Comment by abhi1693** [comment]
This is due to the netbox ui plugin. You should open the bug with the plugin developer.

**Comment by aledr** [comment]
Just found it after filling in the issue here.
Thanks.
