### ISSUE TITLE
Use of FIELD_CHOICES for Status causes REST to fail with KeyError

### ISSUE THREAD

**Issue by moseisleydk** [netbox-community/netbox#12446]
### NetBox version

3.4.7

### Python version

3.10

### Steps to Reproduce

Addeding following code to configuration.py:

FIELD_CHOICES = {
--
'dcim.Device.status': (
('planned', 'Planned', 'cyan'),
('created', 'Created', 'grey'),
('production', 'Production', 'blue'),
('under decommision', 'Under Decommisioning', 'blue'),
('closed', 'Closed', 'blue'),
('in storage', 'In Storage', 'blue'),
('active','Active'),
('offline','Offline'),
('staged','staged'),
('failed','Failed'),
('inventory','Inventory'),
('decommisioning','Decomissioning')
)
}

UI looks and works fine.

Calling REST at: https://netboxtest.netic.dk/api/dcim/devices/

Causes Error:

<class 'KeyError'>

'decommisioning'

Python version: 3.10.6
NetBox version: 3.4.7

### Expected Behavior

That the REST https://netboxtest.netic.dk/api/dcim/devices/ returns a json list of devices.

### Observed Behavior

NetBox throws error:

<class 'KeyError'>

'decommisioning'

Python version: 3.10.6
NetBox version: 3.4.7

**Comment by jeremystretch** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

**Comment by moseisleydk** [comment]
I guess that anyone could add the FIELD_CHOICES to configuration.py on a NetBox Instance, restart it and make the REST .... Its that not sufficient detailed steps?

**Comment by jeremystretch** [comment]
First, please modify your post above to show the exact, valid Python code form your configuration file. Second, please extend the reproduction steps to indicate whether you have created a device prior to modifying the configuration, and if so, what value you have assigned for its status.

**Comment by moseisleydk** [comment]
Hope the improvement is sufficient :-)

**Comment by abhi1693** [comment]
I tried this with the updated steps and the API loads fine on v3.4.7.

**Comment by moseisleydk** [comment]
Ok, sorry to hear that :-(

I see this in the log:

```


etbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \| Internal Server Error: /api/dcim/devices/
--
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \| Traceback (most recent call last):
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     response = get_response(request)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     response = wrapped_callback(request, *callback_args, **callback_kwargs)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     return view_func(*args, **kwargs)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     return self.dispatch(request, *args, **kwargs)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/netbox/netbox/api/viewsets/__init__.py", line 118, in dispatch
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     return super().dispatch(request, *args, **kwargs)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     response = self.handle_exception(exc)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     self.raise_uncaught_exception(exc)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     raise exc
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     response = handler(request, *args, **kwargs)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/netbox/netbox/api/viewsets/__init__.py", line 149, in list
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     return super().list(request, *args, **kwargs)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     return self.get_paginated_response(serializer.data)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     ret = super().data
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     self._data = self.to_representation(self.instance)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     return [
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     self.child.to_representation(item) for item in iterable
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     ret[field.field_name] = field.to_representation(attribute)
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|   File "/opt/netbox/netbox/netbox/api/fields.py", line 51, in to_representation
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \|     'label': self._choices[obj],
netbox_test_netbox.1.ia54n8mn6axj@netbox01.netic.dk    \| KeyError: 'decommissioning'

```

**Comment by abhi1693** [comment]
If you notice correctly, the stackstrace does not match the FIELD_CHOICES and the error you had provided earlier.

From the stackstrace, it says `decommissioning` is not in FIELD_CHOICES which is true as you have provided `decommisioning`.
