### ISSUE TITLE
Upgrade from 3.4.7 to 3.5.0 fail on Applying database migrations

### ISSUE THREAD

**Issue by saschapapini** [netbox-community/netbox#12467]
### NetBox version

v3.5.0

### Python version

3.10

### Steps to Reproduce

I try to update our netbox to new version 3.5.0, when I launch the upgrade command
cd /opt/netbox
sudo ./upgrade.sh

### Expected Behavior

Upgrade done

### Observed Behavior

I receive an error on migrate procedure and upgrade stop
`
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox-3.5.0/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 97, in handle
    self.check(databases=[database])
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox-3.5.0/netbox/netbox/urls.py", line 8, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox-3.5.0/netbox/extras/plugins/urls.py", line 31, in <module>
    urlpatterns = import_string(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/netbox_dns/urls.py", line 6, in <module>
    from netbox_dns.views import (
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/netbox_dns/views/__init__.py", line 1, in <module>
    from .view import *
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/netbox_dns/views/view.py", line 5, in <module>
    from netbox_dns.forms import ViewForm, ViewFilterForm, ViewImportForm, ViewBulkEditForm
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/netbox_dns/forms/__init__.py", line 1, in <module>
    from .view import *
  File "/opt/netbox-3.5.0/venv/lib/python3.10/site-packages/netbox_dns/forms/view.py", line 9, in <module>
    from utilities.forms import TagFilterField
ImportError: cannot import name 'TagFilterField' from 'utilities.forms' (/opt/netbox-3.5.0/netbox/utilities/forms/__init__.py)
`

**Comment by kkthxbye-code** [comment]
The plugin your are using is incompatible with netbox 3.5:

https://github.com/auroraresearchlab/netbox-dns/issues/293
