### ISSUE TITLE
netbox upgrade to 

### ISSUE THREAD

**Issue by tedserreyn** [netbox-community/netbox#14641]
### Deployment Type

Self-hosted

### NetBox Version

V3.7.0

### Python Version

3.9

### Steps to Reproduce

upgrade existing 3.6.9 install
git sync; git checkout master; git pull origin master
# run script
./upgrade.sh 
# restart things
systemctl restart netbox netbox-rq
#

### Expected Behavior

I expected upgrade to complete successfully.

### Observed Behavior

upgrade script failed
Successfully installed bcrypt-4.1.2 dnspython-2.4.2 future-0.18.3 importlib-metadata-4.13.0 ipaddress-1.0.23 jsonschema-3.2.0 macaddress-2.0.2 mypy_extensions-0.4.4 n2g-0.3.3 netbox-ddns-1.2.9 netbox-topology-views-3.8.1 netdoc-3.5.18 netmiko-4.1.2 nornir-3.3.0 nornir-netmiko-0.2.0 nornir-utils-0.2.0 ntc-templates-4.1.0 ouilookup-0.2.4 paramiko-3.4.0 pynacl-1.5.0 pyrsistent-0.20.0 pyserial-3.5 python-slugify-8.0.1 pyvmomi-8.0.1.0.1 ruamel.yaml-0.18.5 ruamel.yaml.clib-0.2.8 scp-0.14.5 tenacity-8.2.3 textfsm-1.1.2 xmltodict-0.13.0
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_topology_views/models.py", line 13, in <module>
    from netbox.models.features import (
ImportError: cannot import name 'WebhooksMixin' from 'netbox.models.features' (/opt/netbox/netbox/netbox/models/features.py)

**Comment by abhi1693** [comment]
This is not a bug with netbox but with the topology views plugin.

**Comment by ekrichbaum** [comment]
https://github.com/mattieserver/netbox-topology-views/issues/430
You can patch it yourself with ThomasADavis' work or wait until the plugin is updated for 3.7.

**Comment by tedserreyn** [comment]
Fixed and resolved.

From: Eric Krichbaum ***@***.***>
Date: Friday, December 29, 2023 at 4:04 PM
To: netbox-community/netbox ***@***.***>
Cc: Ted Serreyn ***@***.***>, Author ***@***.***>
Subject: Re: [netbox-community/netbox] netbox upgrade to (Issue #14641)

mattieserver/netbox-topology-views#430<https://github.com/mattieserver/netbox-topology-views/issues/430>
You can patch it yourself with ThomasADavis' work or wait until the plugin is updated for 3.7.
