### ISSUE TITLE
Ugly exception when validating incorrect IP Address

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox#14724]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.0

### Python Version

3.10

### Steps to Reproduce

Try to create an IP address via script with incorrect address.

```py
>>> ip = IPAddress(address='???')
>>> ip.full_clean()
```

### Expected Behavior

I expect to see a meaningful exception message like this:
```py
django.core.exceptions.ValidationError: ['Invalid IP address format: ???']
```

### Observed Behavior

```py
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1477, in full_clean
    self.clean()
  File "/opt/netbox-3.7.0/netbox/ipam/models/ip.py", line 842, in clean
    if self.address.prefixlen == 0:
AttributeError: 'str' object has no attribute 'prefixlen'
```

**Comment by jeremystretch** [comment]
This is expected to happen when you intentionally pass invalid data directly to an instance without using a form field or serializer. This is the nature of working with the Python ORM directly.

**Comment by llamafilm** [comment]
But this issue seems to be specific to IP Addresses.  For example trying to add a bad MAC address fails with a better error:
```
>>> iface = Device.objects.last().interfaces.first()
>>> iface.mac_address = '123'
>>> iface.full_clean()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/netbox-3.7.0/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'mac_address': ['Invalid MAC address format: 123']}
```
