### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'http_content_type' Webhook Issue

### ISSUE THREAD

**Issue by viperbmw** [netbox-community/netbox#15836]
### Deployment Type

Self-hosted

### NetBox Version

v3.7.6

### Python Version

3.11

### Steps to Reproduce

When we try to send a web hook from an event we get an error in the worker server .

`AttributeError: 'NoneType' object has no attribute 'http_content_type'`

Although we do for sure have the `application/json` set 

We have a Prod and Pre Prod. The issue is only happening on the Prod server. It is the exactly same image and environment. We are running in Docker. 

### Expected Behavior

Expect prod to work like pre prod 

### Observed Behavior

```
RESULT 1713966969876-0

Type:
FAILED
Created at:
2024-04-24, 13:56:09
Exception:
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/worker.py", line 1431, in perform_job
    rv = job.perform()
         ^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1280, in perform
    self._result = self._execute()
                   ^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1317, in _execute
    result = self.func(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/extras/webhooks.py", line 50, in send_webhook
    'Content-Type': webhook.http_content_type,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'http_content_type'
```
```[tasklist]
### Tasks
```

This did work at one point now it's not. No changes where made to the code

**Comment by viperbmw** [comment]
<img width="854" alt="Screenshot 2024-04-24 at 10 07 47 AM" src="https://github.com/netbox-community/netbox/assets/56923316/f90bfa15-6e4f-4b44-b2df-f70acacfe462">
<img width="852" alt="Screenshot 2024-04-24 at 10 07 24 AM" src="https://github.com/netbox-community/netbox/assets/56923316/8256d030-300f-4435-b379-4fcc45dc8bae">

**Comment by viperbmw** [comment]
The issue was I was not pointing to the correct DB
