### ISSUE TITLE
netbox-rq not working with rq 2.0.0

### ISSUE THREAD

**Issue by fggec** [netbox-community/netbox#18001]
### Deployment Type

Self-hosted

### Triage priority

I'm a NetBox Labs customer

### NetBox Version

v4.1.4

### Python Version

3.12

### Steps to Reproduce

Follow the installation instructions with a fresh Ubuntu 24.04 installation.

### Expected Behavior

netbox-rq service is starting correct

### Observed Behavior

Starting the netbox-rq service is resulting in an error if the installed version of rq is 2.0.0

```Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]: Traceback (most recent call last):
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "/opt/netbox/netbox/manage.py", line 10, in <module>
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:     execute_from_command_line(sys.argv)
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:     utility.execute()
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:     self.fetch_command(subcommand).run_from_argv(self.argv)
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 275, in fetch_command
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:     klass = load_command_class(app_name, subcommand)
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 48, in load_command_class
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:     module = import_module("%s.management.commands.%s" % (app_name, name))
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:     return _bootstrap._gcd_import(name[level:], package, level)
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "/opt/netbox-4.1.4/netbox/core/management/commands/rqworker.py", line 3, in <module>
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:     from django_rq.management.commands.rqworker import Command as _Command
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django_rq/management/commands/rqworker.py", line 5, in <module>
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]:     from rq import Connection
Nov 13 12:53:29 vm-int-lab-netbox01 python3[3126]: ImportError: cannot import name 'Connection' from 'rq' (/opt/netbox/venv/lib/python3.12/site-packages/rq/__init__.py). Did you mean: 'connections'?
Nov 13 12:53:29 vm-int-lab-netbox01 systemd[1]: netbox-rq.service: Main process exited, code=exited, status=1/FAILURE```

**Comment by fggec** [comment]
As a quickfix append your local_requirements.txt with the line `rq<2.0.0` and everything should be fine again

**Comment by jeremystretch** [comment]
> v4.1.4

Please upgrade to the current stable release (v4.1.6) as this issue has already been resolved.

**Comment by fggec** [comment]
```Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]: Traceback (most recent call last):
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "/opt/netbox/netbox/manage.py", line 10, in <module>
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:     execute_from_command_line(sys.argv)
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:     utility.execute()
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:     self.fetch_command(subcommand).run_from_argv(self.argv)
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 275, in fetch_command
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:     klass = load_command_class(app_name, subcommand)
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 48, in load_command_class
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:     module = import_module("%s.management.commands.%s" % (app_name, name))
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:     return _bootstrap._gcd_import(name[level:], package, level)
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "/opt/netbox-4.1.6/netbox/core/management/commands/rqworker.py", line 3, in <module>
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:     from django_rq.management.commands.rqworker import Command as _Command
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:   File "/opt/netbox/venv/lib/python3.12/site-packages/django_rq/management/commands/rqworker.py", line 5, in <module>
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]:     from rq import Connection
Nov 14 09:20:57 vm-int-lab-netbox01 python3[3365]: ImportError: cannot import name 'Connection' from 'rq' (/opt/netbox/venv/lib/python3.12/site-packages/rq/__init__.py). Did you mean: 'connections'?
Nov 14 09:20:57 vm-int-lab-netbox01 systemd[1]: netbox-rq.service: Main process exited, code=exited, status=1/FAILURE
```
Computer says NO

**Comment by fggec** [comment]
Ignore my last comment. I got what you meant. 

Not the error is fixed, you fixed the requirements.
