### ISSUE TITLE
Housekeeping for changelogs fails when branching is used

### ISSUE THREAD

**Issue by rcrawf** [netbox-community/netbox#18003]
### Deployment Type

NetBox Cloud

### Triage priority

N/A

### NetBox Version

v4.1.6

### Python Version

3.11

### Steps to Reproduce

- Install [Netbox branching](https://github.com/netboxlabs/netbox-branching) (I used 0.5.2).
- Create a branch, make a change to an object then merge it
- Configure [changelog retention](https://github.com/netbox-community/netbox/blob/develop/docs/administration/housekeeping.md) in `configuration.py`:

```
CHANGELOG_RETENTION = 45
```

- Run `manage.py housekeeping`

### Expected Behavior

Changelogs are deleted. 

### Observed Behavior

The changelog fails to be deleted because of a reference to `netbox_branching_appliedchange`:

```
./manage.py housekeeping
[*] Clearing expired authentication sessions
	Sessions cleared.
[*] Checking for expired changelog records
	Deleting 18 expired records... Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.ForeignKeyViolation: update or delete on table "core_objectchange" violates foreign key constraint "netbox_branching_app_change_id_5ac5eb3f_fk_core_obje" on table "netbox_branching_appliedchange"
DETAIL:  Key (id)=(6) is still referenced from table "netbox_branching_appliedchange".

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/extras/management/commands/housekeeping.py", line 56, in handle
    ObjectChange.objects.filter(time__lt=cutoff)._raw_delete(using=DEFAULT_DB_ALIAS)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1210, in _raw_delete
    cursor = query.get_compiler(using).execute_sql(CURSOR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: update or delete on table "core_objectchange" violates foreign key constraint "netbox_branching_app_change_id_5ac5eb3f_fk_core_obje" on table "netbox_branching_appliedchange"
DETAIL:  Key (id)=(6) is still referenced from table "netbox_branching_appliedchange".
```

**Comment by jeremystretch** [comment]
Please submit any issues involving a plugin under the repo for that plugin.
