### ISSUE TITLE
Unable to load / endpoint when logged out after upgrade from 4.0.11

### ISSUE THREAD

**Issue by YoucefYousfi** [netbox-community/netbox#18156]
### Deployment Type

Self-hosted

### Triage priority

N/A

### NetBox Version

v4.1.7

### Python Version

3.11

### Steps to Reproduce

1. Upgrade Netbox from 4.0.11 to 4.1.7
2. Log out if session remained active
3. Try to load the / URL (like https://<netbox_url>/)

### Expected Behavior

Properly load the URL

### Observed Behavior

I get an error when attempting to do that. I have enabled debug mode and here is the copy-paste of the error (it seems to be related to the change from extras to core for ObjectChanges) :
```
Environment:


Request Method: GET
Request URL: https://<netbox_url>/

Django Version: 5.0.9
Python Version: 3.11.9
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.forms',
 'corsheaders',
 'debug_toolbar',
 'django_filters',
 'django_htmx',
 'django_tables2',
 'django_prometheus',
 'strawberry_django',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'core',
 'account',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'vpn',
 'wireless',
 'django_rq',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'netbox_documents.NetboxDocuments',
 'netbox_secrets.NetBoxSecrets']
Installed Middleware:
['strawberry_django.middlewares.debug_toolbar.DebugToolbarMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django_htmx.middleware.HtmxMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.CoreMiddleware',
 'netbox.middleware.MaintenanceModeMiddleware']


Template error:
In template /app/edited_hostname/netbox-4.1.7/netbox/templates/extras/dashboard/widget.html, error at line 43
   ObjectType matching query does not exist.
   33 :           data-bs-toggle="modal"
   34 :           data-bs-target="#htmx-modal"
   35 :           class="text-bg-{{ bg_color }}"
   36 :           aria-label="{% trans "Close widget" %} {{ widget.title }}"
   37 :         >
   38 :           <i class="mdi mdi-close"></i>
   39 :         </a>
   40 :       </div>
   41 :     {% endwith %}
   42 :     <div class="card-body p-2 pt-1 overflow-auto">
   43 :        {% render_widget widget %} 
   44 :     </div>
   45 :   </div>
   46 : </div>
   47 : 

Traceback (most recent call last):
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/contrib/contenttypes/models.py", line 20, in get_by_natural_key
    ct = self._cache[self.db][(app_label, model)]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception (('extras', 'objectchange')), another exception occurred:
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/netbox/utilities/views.py", line 39, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/netbox/netbox/views/misc.py", line 62, in get
    return render(request, self.template_name, {
           
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/netbox/extras/templatetags/dashboard.py", line 11, in render_widget
    return widget.render(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/netbox/extras/dashboard/widgets.py", line 239, in render
    model = ObjectType.objects.get_by_natural_key(app_label, model_name).model_class()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/contrib/contenttypes/models.py", line 22, in get_by_natural_key
    ct = self.get(app_label=app_label, model=model)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edited_hostname/netbox-4.1.7/venv/lib64/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
    ^

Exception Type: DoesNotExist at /
Exception Value: ObjectType matching query does not exist.
```

**Comment by arthanson** [comment]
@YoucefYousfi is it only on the main page? Does it error if you go to a sub-page like `/dcim/devices/`?  I'm wondering if you have a custom dashboard widget that is potentially causing issues.
