### ISSUE TITLE
Upgrade from 2.6.1 to 2.6.2 broke netbox

### ISSUE THREAD

**Issue by jameswhite4684** [netbox-community/netbox#3410]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.2
* pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

Used the upgrade script this morning and after the upgrade I received a 500 Internal Server Error.

This command no longer works: sudo supervisorctl restart netbox

I probably really broke it now after trying several fixes.

I get this out put using this command: 
"python3 manage.py runserver 0.0.0.0:8000 --insecure"

Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 398, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 6, in <module>
    from drf_yasg.views import get_schema_view
  File "/usr/local/lib/python3.6/dist-packages/drf_yasg/views.py", line 14, in <module>
    from .renderers import (
  File "/usr/local/lib/python3.6/dist-packages/drf_yasg/renderers.py", line 11, in <module>
    from .codecs import VALIDATORS, OpenAPICodecJson, OpenAPICodecYaml
  File "/usr/local/lib/python3.6/dist-packages/drf_yasg/codecs.py", line 133, in <module>
    class SaneYamlDumper(yaml.SafeDumper):
AttributeError: module 'ruamel.yaml' has no attribute 'SafeDumper'

### Steps to Reproduce
1.
2.
3.

**Comment by DanSheps** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by jameswhite4684** [comment]
Really, how can I reproduce if it broke.

**Comment by DanSheps** [comment]
This is an issue for the mailing list, it is not a reproducible bug
