### ISSUE TITLE
Error on startup Netbox application

### ISSUE THREAD

**Issue by leon-developer-br** [netbox-community/netbox#3928]
Hi, 

I am starting the container with docker-compose up -d and in the netbox_1 container i am catching this error on connection with Redis

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/netbox/netbox/extras/apps.py", line 33, in ready
    "Unable to connect to the Redis database. Check that the Redis configuration has been defined in "
django.core.exceptions.ImproperlyConfigured: Unable to connect to the Redis database. Check that the Redis configuration has been defined in configuration.py.
⏳ Waiting on DB...

**Comment by hSaria** [comment]
This will end up closed if you don't format it according to one of the existing issue templates, plus it's kind of irrelevant as this isn't the [netbox-docker](https://github.com/netbox-community/netbox-docker) repo, but...

> Check that the Redis configuration has been defined in configuration.py

Surely this might be a clue as to what needs to be done (check out `netbox/netbox/configuration.example.py`)

**Comment by leon-developer-br** [comment]
Sorry

**Comment by hSaria** [comment]
I didn't mean to be hostile; it's just that the issue becomes more unreadable the less it resembles a template.
