### ISSUE TITLE
NetBox error creating the DB schema

### ISSUE THREAD

**Issue by AfraduaR** [netbox-community/netbox#4082]
### Environment
* Python version: 3.6.9 
* NetBox version: 2.7.3 

### Steps to Reproduce
1. Installing Netbox on ubuntu 18.04 LTS under virtualbox 
2. Modified configuration.py for ALLOWED_HOSTS =/ DATABASE = / SECRET_KEY =
3. create DB schema: sudo python3 /opt/netbox/netbox/manage.py migrate

### Expected Behavior
Creation of DB schema

### Observed Behavior
alvaro@alvaro-VirtualBox:/opt/netbox/netbox$ sudo python3 /opt/netbox/netbox/manage.py migrate
[sudo] password for alvaro: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 539, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 596, in _connect
    raise err
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox-2.7.3/netbox/extras/apps.py", line 23, in ready
    rs.ping()
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1106, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/netbox-2.7.3/netbox/extras/apps.py", line 26, in ready
    "Unable to connect to the Redis database. Check that the Redis configuration has been defined in "
django.core.exceptions.ImproperlyConfigured: Unable to connect to the Redis database. Check that the Redis configuration has been defined in configuration.py.

**Comment by hSaria** [comment]
It appears you haven't configured the `REDIS` key appropriately. Questions like these are best suited for the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss); people are faster to answer them there.

**Comment by jeremystretch** [comment]
Yep, this is an installation error. Please post to the mailing list if you require any further assistance.
