### ISSUE TITLE
Webhooks Failing 

### ISSUE THREAD

**Issue by robduffy2010** [netbox-community/netbox#4452]
### Environment
* Python version: 3.6.10
* NetBox version: 2.7.11

### Steps to Reproduce
1. Create a webhook without any custom body or headers
2. Edit device (I've only tested with devices but may also happen with other objects)
3. Observe webhook failing 

### Expected Behavior
Webhook will succeed.

### Observed Behavior
Webhooks fail and raise the following exception.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 884, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.6/dist-packages/rq/job.py", line 664, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/rq/job.py", line 670, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/opt/netbox/netbox/extras/webhooks_worker.py", line 32, in process_webhook
    headers.update(webhook.render_headers(context))
AttributeError: 'Webhook' object has no attribute 'render_headers'

**Comment by jeremystretch** [comment]
Unable to replicate this on v2.7.11. Ensure that you've restarted the rqworker process since the last upgrade. If you need further assistance, please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
