### ISSUE TITLE
Webhooks UTF-8 trouble

### ISSUE THREAD

**Issue by proudbro** [netbox-community/netbox#4549]
### Environment
* Python version: 3.6.9
* NetBox version: 2.8.1

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Create webhook 
Object Type: Tenant 
HTTP content type: application/json
HTTP method: POST
Additional headers: _No Additional Headers_
Body template: `{"text": " [{{model}}] Name:{{data['name']}}, ID:{{data['id']}} was {{event}} by {{username}}"}`
3. Create a Tenant object with Cyrillic Symbols in NAME field 

### Expected Behavior
Successfully get a webhook as we received before with latin symbols

### Observed Behavior
Go into Failed Jobs in Admin panel and see Exception in job info:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 884, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.6/dist-packages/rq/job.py", line 664, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/rq/job.py", line 670, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/opt/netbox/netbox/extras/webhooks_worker.py", line 72, in process_webhook
    response = session.send(prepared_request)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1309, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib/python3.6/http/client.py", line 171, in _encode
    (name.title(), data[err.start:err.end], name)) from None
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 25-28: Body ('ТЕСТ') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

**Comment by kobayashi** [comment]
I can reproduce this issue.
Similar issue was opened in https://github.com/psf/requests/issues/1822
