### ISSUE TITLE
Internal Server Error during create new ip-address via API or pynetbox

### ISSUE THREAD

**Issue by heineek** [netbox-community/netbox#4610]
### Environment
* Python version: 3.8.0
* NetBox version: 2.8.1

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Try to add new ip-address using pynetbox method nb.ipam.ip_addresses.create(data)
OR
3. Try to add new ip-address using built-in Swagger interface

### Expected Behavior
The new IP-address would be crerated

### Observed Behavior
Error 500: Internal Server Error and the following messages in log file:

```
Internal Server Error: /api/ipam/ip-addresses/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/api.py", line 330, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/serializers.py", line 235, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/serializers.py", line 430, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/serializers.py", line 487, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/fields.py", line 539, in run_validation
    (is_empty_value, data) = self.validate_empty_values(data)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/fields.py", line 515, in validate_empty_values
    return (True, self.get_default())
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/fields.py", line 493, in get_default
    return self.default()
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/fields.py", line 264, in __call__
    return self.default()
TypeError: __call__() missing 1 required positional argument: 'serializer_field'
```

Note: updating the existing ip-address object with the same data dictionary is successful. Also if I try to create the IP-address manually via web interface all is OK: ip-address creates without any errors.

**Comment by kobayashi** [comment]
Could you let us know the POST data to reproduce?

While trying this through swagger ui, it worked.
```
{
  "address": "10.0.0.2/24"
}
```

**Comment by heineek** [comment]
I try to POST this data:
{'address': '100.104.15.169/25'}

> 10.0.0.2/24

I've tried to add this address via Swagger, but the same error happens.
I can add any IP-address manually only from web form. In the same time PATH, PUT and DELETE methods work. Only POST method doesn't work now. My python code and dependencies have not been changed a long time ago, observed behavior began after upgrading the NetBox to version 2.8.1.

**Comment by kobayashi** [comment]
I tried with the same version and could not reproduce. As you mentioned your dependency may related, can you try to upgrade? [This page](https://netbox.readthedocs.io/en/stable/installation/upgrading/) may be helpful.
GitHub issues are intended for reporting reproducible bugs and requesting features. For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by heineek** [comment]
So, I've resolved. After introducing the virtual environment you MUST edit /etc/systemd/system/netbox*.service and change the beginnigs of ExecParameter from "/usr/bin/[gunicorn, python3]..." to "/opt/netbox/venv/bin/[gunicorn, pyhton]...". The error described above happened because I did not edit these files and my NetBox used old versions of libraries from global environment instead its own one.
