### ISSUE TITLE
Server error when trying to view "Inventory Items" list

### ISSUE THREAD

**Issue by hoalex** [netbox-community/netbox#4634]
### Environment
* Python version: 3.6.8
* NetBox version: 2.8.3

### Steps to Reproduce
1. Disable any installed plugins by commenting out the `PLUGINS` setting in
   `configuration.py`.
2. Navigate to `Devices` -> `Inventory Items`

### Expected Behavior
A list of all inventory items should appear.

### Observed Behavior
A server error appears:

![2020-05-13 08_36_11-Server Error](https://user-images.githubusercontent.com/6103894/81779514-282a9880-94f5-11ea-910d-8b73b9e4b1cd.png)
```
<class 'ValueError'>

'manufacturer__name' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
```

**Comment by jeremystretch** [comment]
I'm not able to replicate this by simply navigating to the view. Can you please provide more detail as to specifically what you're doing? Does it still occur if you reset your table configuration (Configure -> Reset)? Also, can you please post the complete stack trace?

**Comment by matte4711** [comment]
This is the stacktrace from our staging instance of Netbox. 

```
Template error:
In template /opt/netbox/netbox/templates/inc/table.html, error at line 18
   'manufacturer__name' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
   8 :                     {% if column.orderable %}
   9 :                         <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a></th>
   10 :                     {% else %}
   11 :                         <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
   12 :                     {% endif %}
   13 :                 {% endfor %}
   14 :             </tr>
   15 :         </thead>
   16 :     {% endif %}
   17 :     <tbody>
   18 :          {% for row in table.page.object_list|default:table.rows %} 
   19 :             <tr {{ row.attrs.as_html }}>
   20 :                 {% for column, cell in row.items %}
   21 :                     <td {{ column.attrs.td.as_html }}>{{ cell }}</td>
   22 :                 {% endfor %}
   23 :             </tr>
   24 :         {% empty %}
   25 :             {% if table.empty_text %}
   26 :                 <tr>
   27 :                     <td colspan="{{ table.columns|length }}" class="text-center text-muted">&mdash; {{ table.empty_text }} &mdash;</td>
   28 :                 </tr>


Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/views.py", line 194, in get
    return render(request, self.template_name, context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/defaulttags.py", line 513, in render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django_tables2/templatetags/django_tables2.py", line 167, in render
    return template.render(context={"table": table}, request=request)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/defaulttags.py", line 161, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 697, in resolve
    new_obj = func(obj, *arg_vals)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/defaultfilters.py", line 754, in default
    return value or arg
  File "/opt/netbox/venv/lib/python3.7/site-packages/django_tables2/rows.py", line 330, in __len__
    length = len(self.data)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/opt/netbox/venv/lib/python3.7/site-packages/cacheops/query.py", line 323, in _fetch_all
    return self._no_monkey._fetch_all(self)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1263, in _fetch_all
    self._prefetch_related_objects()
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/models/query.py", line 782, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1648, in prefetch_related_objects
    "prefetch_related()." % lookup.prefetch_through)

Exception Type: ValueError at /dcim/inventory-items/
Exception Value: 'manufacturer__name' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
```

**Comment by hoalex** [comment]
For me, this error occurs immediately upon clicking on the "Inventory Items" link in the navbar.
I cleared all user preferences (which should also clear the table column configuration) and restarted netbox-rq and netbox. The problem is still the same.

I confirm that my stacktrace looks like the one posted by @matte4711 above.

**Comment by DanSheps** [comment]
Steps to reproduce:

1. Create a device
2. Create a inventory item **with** a manufacturer
3. Navigate to the "Inventory Items" list view

**Comment by hoalex** [comment]
You're right! I removed the manufacturer from my inventory items, afterwards the "Inventory items" list view loaded just fine.

**Comment by DanSheps** [comment]
Root cause:


    manufacturer = tables.Column(
        accessor=Accessor('manufacturer.name')
    )

Should be


    manufacturer = tables.Column(
        accessor=Accessor('manufacturer__name')
    )

as per the docs for django_tables2

**Comment by DanSheps** [comment]
> You're right! I removed the manufacturer from my inventory items, afterwards the "Inventory items" list view loaded just fine.

Please make sure you are providing complete steps to reproduce in the future.  When in doubt, you can always test on https://master.netbox.dev

**Comment by hoalex** [comment]
Will do. To be honest, I did not make the mental link between having a specific inventory item configuration, and this error message. I carried over this inventory item configuartion since some versions, and probably only now tried to open the corresponding list view.
Next time, I will try to reproduce it on the demo site first.
