### ISSUE TITLE
Error when multi-edit 802.1Q Mode

### ISSUE THREAD

**Issue by fmaytain** [netbox-community/netbox#5136]
### Environment
* Python version: 3.6.9
* NetBox version: 2.9.3

### Steps to Reproduce
1. navigate to a device (e.g. /dcim/devices/3/)
2. select checkboxes next to one or more interfaces
3. click Edit (goes to /dcim/interfaces/edit/?device=3&return_url=/dcim/devices/3/)
4. set access mode Tagged (All)
5. click Apply

Interface accordingly tagged.

<class 'TypeError'>
count() takes exactly one argument (0 given)
Python version: 3.6.9
NetBox version: 2.9.3

Backtrace:
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/views.py", line 123, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/views.py", line 948, in post
    if form.cleaned_data[name].count() > 0:

Exception Type: TypeError at /dcim/interfaces/edit/
Exception Value: count() takes exactly one argument (0 given)
Request information:
USER: admin

GET:
device = '3'
return_url = '/dcim/devices/3/'

POST:
csrfmiddlewaretoken = 'XXXX'
pk = '22'
label = ''
type = ''
enabled = 'on'
lag = ''
mac_address = ''
mtu = ''
description = ''
mode = 'tagged-all'
untagged_vlan = ''
_apply = ''

**Comment by jeremystretch** [comment]
Looks like a regression introduced by a12d94a3bcb074cd769d85c94b0eeade7ceee483 under #4880.
