### ISSUE TITLE
Creating interfaces in bulk for virtual machines results in a server error

### ISSUE THREAD

**Issue by barmalej1** [netbox-community/netbox#5221]
### Environment
* Python version: 3.7.9
* NetBox version: 2.9.4

### Steps to Reproduce
1. Select one or multiple VMs
2. Select Add components -> Interfaces on the bottom
3. Put anything in the Name field and click create

### Expected Behavior
New interface should have been created for every selected VM

### Observed Behavior
Received the following error:
----
Server Error

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'KeyError'>

'label_pattern'

Python version: 3.7.9
NetBox version: 2.9.4

If further assistance is required, please post to the NetBox mailing list. 
----
I only tried to create bulk interfaces for servers and virtual machines, servers work fine. I can create an interface for Virtual Machine only from Virtual Machine view

**Comment by DanSheps** [comment]
```
Environment:


Request Method: POST
Request URL: https://master.netbox.dev/virtualization/virtual-machines/interfaces/add/

Django Version: 3.1
Python Version: 3.6.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'debug_toolbar',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'mptt',
 'rest_framework',
 'taggit',
 'timezone_field',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'secrets',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'django_rq',
 'drf_yasg']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'utilities.middleware.ExceptionHandlingMiddleware',
 'utilities.middleware.RemoteUserMiddleware',
 'utilities.middleware.LoginRequiredMiddleware',
 'utilities.middleware.APIVersionMiddleware',
 'extras.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/netbox/master/netbox/utilities/views.py", line 123, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/netbox/master/netbox/utilities/views.py", line 1355, in post
    labels = data['label_pattern']

Exception Type: KeyError at /virtualization/virtual-machines/interfaces/add/
Exception Value: 'label_pattern'
```
