### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by kilker12** [netbox-community/netbox#5254]
### Environment
* Python version: 3.8.5
* NetBox version: 2.9.7

### Steps to Reproduce
1. Install clean netbox instance using install instructions
2. Clone animal_sounds plugin and install using python3 setup.py install
3. Run python3 manage.py collectstatic

### Expected Behavior
python3 manage.py collectstatic to not produce errors

### Observed Behavior
(venv) root@netbox-test:/opt/netbox-animal-sounds# python3 /opt/netbox/netbox/manage.py collectstatic
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-2.9.7/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-2.9.7/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/netbox-2.9.7/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox-2.9.7/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/netbox-2.9.7/netbox/extras/plugins/__init__.py", line 64, in ready
    template_extensions = import_object(f"{self.__module__}.{self.template_extensions}")
  File "/opt/netbox-2.9.7/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
AttributeError: 'zipimporter' object has no attribute 'exec_module'

**Comment by DanSheps** [comment]
This looks like it is related to setuptools installing the plugin as an egg.  There are two options, we require all modules to be deployed with zip_safe=False or we alter our loader to accommodate it.  Here is some potentially relevant code:

https://github.com/python-mode/python-mode/blob/0.10.0/pymode/libs/pkg_resources/__init__.py#L2190-L2205

**Comment by DanSheps** [comment]
I have prodded python regarding this issue under https://bugs.python.org/issue19699

**Comment by kilker12** [comment]
@DanSheps is there any workaround in the mean time?
