### ISSUE TITLE
Issue when upgrading from 2.6.12 to 2.9.9

### ISSUE THREAD

**Issue by jc121985** [netbox-community/netbox#5334]
The environment in which NetBox is running:
2.6.12

The exact steps that can be taken to reproduce the issue:
-Verified dependencies are fine
-Tried both option A and B for upgrade methods on https://netbox.readthedocs.io/en/stable/installation/upgrading/

Any error messages generated:
Applying database migrations (python3 netbox/manage.py migrate)...
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, tenancy, users, virtualization
Running migrations:
  Applying virtualization.0016_replicate_interfaces...
    Replicating 311 VM interfaces...
Traceback (most recent call last):
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "virtualization_vminterfa_virtual_machine_id_name_cfb9c423_uniq"
DETAIL:  Key (virtual_machine_id, name)=(1, Network Adapter 1) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 245, in handle
    fake_initial=fake_initial,
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/netbox-new/netbox-2.9.9/netbox/virtualization/migrations/0016_replicate_interfaces.py", line 37, in replicate_interfaces
    VMInterface.objects.bulk_create(new_interfaces, batch_size=1000)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/cacheops/query.py", line 374, in bulk_create
    objs = self._no_monkey.bulk_create(self, objs, *args, **kwargs)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/models/query.py", line 507, in bulk_create
    objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts,
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1269, in _batched_insert
    ignore_conflicts=ignore_conflicts,
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/cacheops/transaction.py", line 93, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox-new/netbox-2.9.9/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "virtualization_vminterfa_virtual_machine_id_name_cfb9c423_uniq"
DETAIL:  Key (virtual_machine_id, name)=(1, Network Adapter 1) already exists.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/netbox-community/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
