### ISSUE TITLE
Creating a component template throws an exception

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#5458]
### Environment
* Python version: 3.6
* NetBox version: 2.10

### Steps to Reproduce
1. Create a manufacuter
2. Create a device type
3. Click on the Add interface/power port/etc under the appropriate tab ("Add Components" does not experience this issue)
4. Create a interface/power port/etc
5. Fill out required fields
6. Submit

### Expected Behavior
Returns to device type on appropriate tab

### Observed Behavior

Exception:

```<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for '#tab_powerports' not found. '#tab_powerports' is not a valid view function or pattern name.

Python version: 3.6.6
NetBox version: 2.10.0```

**Comment by DanSheps** [comment]
```Environment:


Request Method: POST
Request URL: https://master.netbox.dev/dcim/interface-templates/add/?device_type=&return_url=%23tab_interfaces

Django Version: 3.1.3
Python Version: 3.6.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'debug_toolbar',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'mptt',
 'rest_framework',
 'taggit',
 'timezone_field',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'secrets',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'django_rq',
 'drf_yasg']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'netbox.middleware.ExceptionHandlingMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.LoginRequiredMiddleware',
 'netbox.middleware.APIVersionMiddleware',
 'netbox.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/netbox/master/netbox/utilities/views.py", line 91, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/netbox/master/netbox/netbox/views/generic.py", line 1117, in post
    return redirect(self.get_return_url(request))
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/shortcuts.py", line 131, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/local/netbox/master/venv/lib64/python3.6/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /dcim/interface-templates/add/
Exception Value: Reverse for '#tab_interfaces' not found. '#tab_interfaces' is not a valid view function or pattern name.
```
