### ISSUE TITLE
netbox-2.10-beta1 migration

### ISSUE THREAD

**Issue by zeroservices** [netbox-community/netbox#5742]
### Environment
* Python version: 3.6.8
* NetBox version: 2.10-beta1

### Steps to Reproduce
1. upgrade from 2.10-beta1 to any later version (2.10-beta2, 2.10.0,...)
2. run upgrade.sh

### Expected Behavior
successful db migration

### Observed Behavior
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/netbox/releases/netbox-2.10.4/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/srv/netbox/releases/netbox-2.10.4/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/netbox/releases/netbox-2.10.4/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/netbox/releases/netbox-2.10.4/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/srv/netbox/releases/netbox-2.10.4/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/srv/netbox/releases/netbox-2.10.4/venv/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "/srv/netbox/releases/netbox-2.10.4/venv/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 306, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration ipam.0041_routetarget is applied before its dependency extras.0052_customfield_cleanup on database 'default'.

**Comment by DanSheps** [comment]
Beta Versions are not supported in production.

**Comment by jeremystretch** [comment]
From the beta release notes:

> **WARNING:** This is a beta release and is not suitable for production use. It is intended for development and evaluation purposes only. No upgrade path to the final v2.10 release will be provided from this beta, and users should assume that all data entered into the application will be lost.
