### ISSUE TITLE
Install Command Fails, Usually Segmentation fault

### ISSUE THREAD

**Issue by online-stuff** [netbox-community/netbox#6807]
### NetBox version

v2.11.9

### Python version

3.7

### Steps to Reproduce

Hyper-V  2012r2 Host.
Debian 10.10 Guest OS
Dynamic or Fixed RAM makes no difference.

ESXi Host, install is flawless.

https://netbox.readthedocs.io/en/stable/installation/

Option B during NetBox installation.

The `sudo /opt/netbox/upgrade.sh` command always fails, rarely at the same place.

T

### Expected Behavior

I expected the command to complete successfully.

### Observed Behavior

`  Applying secrets.0003_unicode_literals... OK
  Applying secrets.0004_tags... OK
  Applying secrets.0005_change_logging...Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 246, in handle
    fake_initial=fake_initial,
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/migrations/migration.py", line 116, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 234, in state_forwards
    state.reload_model(app_label, self.model_name_lower, delay=delay)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/migrations/state.py", line 156, in reload_model
    self._reload(related_models)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/migrations/state.py", line 189, in _reload
    self.apps.render_multiple(states_to_be_rendered)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/migrations/state.py", line 305, in render_multiple
    model.render(self)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/migrations/state.py", line 572, in render
    return type(self.name, bases, body)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/models/base.py", line 161, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/netbox/venv/lib/python3.7/site-packages/taggit/managers.py", line 515, in contribute_to_class
    resolve_related_class, cls, self.through, field=self
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/models/fields/related.py", line 80, in lazy_related_operation
    return apps.lazy_model_operation(partial(function, **kwargs), *model_keys)
UnboundLocalError: local variable 'function' referenced before assignment
`

But usually just a Segmentation fault,

`  Applying dcim.0090_cable_termination_models... OK
  Applying dcim.0091_interface_type_other... OK
  Applying dcim.0092_fix_rack_outer_unit... OK
  Applying dcim.0093_device_component_ordering.../opt/netbox/upgrade.sh: line 62:  9988 Segmentation fault      python3 netbox/manage.py migrate
`

**Comment by jeremystretch** [comment]
Per the note displayed when opening an issue, please don't open bug reports for help with installation issues.
