### ISSUE TITLE
Exception when interface connected to bridge with no _path on bridged interface (Bridge, Virtual, etc)

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox#8003]
### NetBox version

v3.1.0

### Python version

3.8

### Steps to Reproduce

1. Create device 1
2. Create Interface 1 (1GE) on device 1
3. Create device 2
4. Create Interface 2 (1GE) on device 2
5. Connect Interface 1 to Interface 2
6. Create Interface 'Bridge' (Bridge) on device 2
7. Edit Interface 2 and bridge to 'Bridge'
8. Attempt cable trace

### Expected Behavior

Cable trace to end at Interface 2 or 'Bridge'

### Observed Behavior

Exception (More detail in comments)

```
Environment:


Request Method: GET
Request URL: https://netbox.uwinnipeg.ca/api/dcim/interfaces/36562/trace/?render=svg

Django Version: 3.2.9
Python Version: 3.8.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'debug_toolbar',
 'graphiql_debug_toolbar',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'graphene_django',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'wireless',
 'django_rq',
 'drf_yasg',
 'netbox_cisco_sync.NetboxCiscoSync',
 'netbox_plugin_extensions.NetboxPluginExtensions',
 'netbox_config_backup.NetboxConfigBackup']
Installed Middleware:
['graphiql_debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'netbox.middleware.ExceptionHandlingMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.LoginRequiredMiddleware',
 'netbox.middleware.DynamicConfigMiddleware',
 'netbox.middleware.APIVersionMiddleware',
 'netbox.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/netbox/netbox/netbox/api/views.py", line 201, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/netbox/netbox/dcim/api/views.py", line 59, in trace
    drawing = obj.get_trace_svg(
  File "/usr/local/netbox/netbox/dcim/models/device_components.py", line 215, in get_trace_svg
    return trace.render()
  File "/usr/local/netbox/netbox/dcim/svg.py", line 466, in render
    near_end, connector, far_end = segment

Exception Type: TypeError at /api/dcim/interfaces/36562/trace/
Exception Value: cannot unpack non-iterable Interface object
```

**Comment by DanSheps** [comment]
```
Environment:


Request Method: GET
Request URL: https://netbox.uwinnipeg.ca/api/dcim/interfaces/36562/trace/?render=svg

Django Version: 3.2.9
Python Version: 3.8.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'debug_toolbar',
 'graphiql_debug_toolbar',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'graphene_django',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'wireless',
 'django_rq',
 'drf_yasg',
 'netbox_cisco_sync.NetboxCiscoSync',
 'netbox_plugin_extensions.NetboxPluginExtensions',
 'netbox_config_backup.NetboxConfigBackup']
Installed Middleware:
['graphiql_debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'netbox.middleware.ExceptionHandlingMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.LoginRequiredMiddleware',
 'netbox.middleware.DynamicConfigMiddleware',
 'netbox.middleware.APIVersionMiddleware',
 'netbox.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/netbox/netbox/netbox/api/views.py", line 201, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/netbox/venv/lib64/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/netbox/netbox/dcim/api/views.py", line 59, in trace
    drawing = obj.get_trace_svg(
  File "/usr/local/netbox/netbox/dcim/models/device_components.py", line 215, in get_trace_svg
    return trace.render()
  File "/usr/local/netbox/netbox/dcim/svg.py", line 466, in render
    near_end, connector, far_end = segment

Exception Type: TypeError at /api/dcim/interfaces/36562/trace/
Exception Value: cannot unpack non-iterable Interface object
```

Due to interaction between:

https://github.com/netbox-community/netbox/blob/d59847537dce2f413378e6d3e474fdc643b332f3/netbox/dcim/models/device_components.py#L196

and 

https://github.com/netbox-community/netbox/blob/d59847537dce2f413378e6d3e474fdc643b332f3/netbox/dcim/models/device_components.py#L205

Since there is no path but the bridge exists, the loop continues but returns a non-tuple.

`return path` should be `return list(zip(*[iter(path)] * 3))`

Perhaps @jeremystretch can double check me on this.

**Comment by jeremystretch** [comment]
> `return path` should be `return list(zip(*[iter(path)] * 3))`

Essentially; we can just `break` out of the loop if `path` is None.
