### ISSUE TITLE
Failed to update nextbox from 2.6.11 to 2.11.10

### ISSUE THREAD

**Issue by isweluiz** [netbox-community/netbox#8923]
### NetBox version

v2.11.10

### Python version

3.8

### Steps to Reproduce

Versions: 
Python version: 3.8.10
NetBox version: 2.6.11

Upgraded Netbox from version 2.6.11 to 2.11.10
Run  ./upgrade.sh

### Expected Behavior

It should migrate the database and start

### Observed Behavior

The database migration fails with an error. See log below: 

```bash
...
...
Installing collected packages: pytz, netaddr, itypes, funcy, certifi, zipp, wrapt, urllib3, uritemplate, tablib, svgwrite, sqlparse, six, ruamel.yaml.clib, PyYAML, pyrsistent, pyparsing, pycryptodome, psycopg2-binary, prometheus-client, Pillow, MarkupSafe, Markdown, inflection, idna, gunicorn, click, charset-normalizer, attrs, asgiref, ruamel.yaml, requests, packaging, Jinja2, importlib-resources, django-prometheus, django-pglocks, Django, deprecated, redis, jsonschema, djangorestframework, django-timezone-field, django-taggit, django-tables2, django-js-asset, django-filter, django-debug-toolbar, django-cors-headers, coreschema, swagger-spec-validator, rq, django-mptt, django-cacheops, coreapi, drf-yasg, django-rq
Successfully installed Django-3.2.5 Jinja2-3.0.1 Markdown-3.3.4 MarkupSafe-2.1.1 Pillow-8.3.1 PyYAML-5.4.1 asgiref-3.5.0 attrs-21.4.0 certifi-2021.10.8 charset-normalizer-2.0.12 click-8.0.4 coreapi-2.3.3 coreschema-0.0.4 deprecated-1.2.13 django-cacheops-6.0 django-cors-headers-3.7.0 django-debug-toolbar-3.2.1 django-filter-2.4.0 django-js-asset-2.0.0 django-mptt-0.12.0 django-pglocks-1.0.4 django-prometheus-2.1.0 django-rq-2.4.1 django-tables2-2.4.0 django-taggit-1.5.1 django-timezone-field-4.1.2 djangorestframework-3.12.4 drf-yasg-1.20.0 funcy-1.17 gunicorn-20.1.0 idna-3.3 importlib-resources-5.4.0 inflection-0.5.1 itypes-1.2.0 jsonschema-4.4.0 netaddr-0.8.0 packaging-21.3 prometheus-client-0.13.1 psycopg2-binary-2.9.1 pycryptodome-3.10.1 pyparsing-3.0.7 pyrsistent-0.18.1 pytz-2022.1 redis-4.1.4 requests-2.27.1 rq-1.10.1 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.6 six-1.16.0 sqlparse-0.4.2 svgwrite-1.4.1 swagger-spec-validator-2.7.4 tablib-3.0.0 uritemplate-4.1.1 urllib3-1.26.9 wrapt-1.14.0 zipp-3.7.0
Skipping local dependencies (local_requirements.txt not found)
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/core/management/base.py", line 86, in wrapped
    saved_locale = translation.get_language()
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 254, in get_language
    return _trans.get_language()
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox-2.11.10/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox-2.11.10/netbox/netbox/settings.py", line 209, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: REDIS section in configuration.py is missing the 'tasks' subsection.
```

**Comment by jeremystretch** [comment]
Reminder, per the issue template:

> If you're having trouble with installation or just looking for assistance with using NetBox, please visit our [discussion forum](https://github.com/netbox-community/netbox/discussions) instead.

Also:

```
django.core.exceptions.ImproperlyConfigured: REDIS section in configuration.py is missing the 'tasks' subsection.
```

This error reports exactly what the problem is.

**Comment by isweluiz** [comment]
> Also:

Yes, I added the correct config on configuration.py, thanks to remember. 

REDIS = {
    'tasks': {
..
..
